
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
base_sepolia = "${BASE_SEPOLIA_RPC}"
