
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@uniswap/v3-periphery/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/=lib/v3-core/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
base_sepolia = "${BASE_SEPOLIA_RPC}"
